[server]
headless = true
runOnSave = false
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 1
maxMessageSize = 8
enableStaticServing = false
disconnectedSessionTTL = 60

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[theme]
base = "light"
primaryColor = "#CC0700"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#374151"
font = "sans serif"
